apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-main
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:eduloginc/karros-devops.git
    targetRevision: HEAD
    path: env/dev



