{{- if and .Values.prometheus.enabled .Values.prometheus.thanosSecret.enabled }}
{{- $secretName := printf "prometheus-%s-extra" (include "kube-prometheus-stack.fullname" . ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default $secretName .Values.prometheus.thanosSecret.name }}
  namespace: {{ .Values.prometheus.namespace }}
{{- if .Values.prometheus.thanosSecret.annotations }}
  annotations:
{{ toYaml .Values.prometheus.thanosSecret.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
    app.kubernetes.io/component: prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
data:
  objstore.yml: |-
{{ .Files.Get (printf "%s" .Values.prometheus.thanosSecret.configFile ) | b64enc | indent 4 }}
{{- end }}