# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  licenses: Apache-2.0
  images: |
    - name: argo-cd
      image: docker.io/bitnami/argo-cd:2.11.3-debian-12-r4
    - name: dex
      image: docker.io/bitnami/dex:2.40.0-debian-12-r2
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r24
    - name: redis
      image: docker.io/bitnami/redis:7.2.5-debian-12-r2
apiVersion: v2
appVersion: 2.11.3
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Argo CD is a continuous delivery tool for Kubernetes based on GitOps.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/argo-cd/img/argo-cd-stack-220x234.png
keywords:
- Continuous delivery
- Continuous deployment
- Devops
- Kubernetes
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: argo-cd
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/argo-cd
version: 6.5.2
