### Backend MongoDB ###
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-mongodb
  namespace: argocd

spec:
  destination:
    namespace: dev
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-charts/mongodb
    helm:
      valueFiles:
      - mongodb.yaml
      parameters: []
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

### Web App ###
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-web-app
  namespace: argocd

spec:
  destination:
    namespace: dev
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-charts/web-app
    helm:
      valueFiles:
      - web-app.yaml
      parameters: []
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

####### LOGGING #######
# Elasticsearch #
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-elasticsearch
  namespace: argocd

spec:
  destination:
    namespace: logging
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-charts/elasticsearch
    helm:
      valueFiles:
      - elsa-values.yaml
      parameters: []
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# Logstash #
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-logstash
  namespace: argocd

spec:
  destination:
    namespace: logging
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-charts/logstash
    helm:
      valueFiles:
      - elsa-values.yaml
      parameters: []
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# Kibana #
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kibana
  namespace: argocd

spec:
  destination:
    namespace: logging
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-charts/kibana
    helm:
      valueFiles:
      - elsa-values.yaml
      parameters: []
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# Filebeat #
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-filebeat
  namespace: argocd

spec:
  destination:
    namespace: logging
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-charts/filebeat
    helm:
      valueFiles:
      - elsa-values.yaml
      parameters: []
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

####### Monitoring #######
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-kube-prometheus-stack
  namespace: argocd

spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-charts/kube-prometheus-stack
    helm:
      valueFiles:
      - elsa-values.yaml
      parameters: []
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true